- hosts: all 
  vars:
    php_version: "7.4"
  tasks:
  - name: Disable SELinux
    selinux:
      state: disabled
    when: ansible_facts['os_family'] == "RedHat"
  
  - include_tasks: php.yml
    when: group_names.0 == "web"
  
  - include_tasks: apache.yml
    when: group_names.0 == "web"
  
  - include_tasks: wordpress.yml
    when: group_names.0 == "web"
  
  - include_tasks: mysql.yml
    when: group_names.0 == "db"