- name: Download WordPress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /var/www/html/
    remote_src: True

- name: Change apache root directory
  replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: '"/var/www/html"'
    replace: '"/var/www/html/wordpress"'
    backup: yes
  when: ansible_facts['os_family'] == "RedHat"
  
- name: moving files 
  ansible.builtin.shell: 
    cmd: mv /var/www/html/wordpress/* /var/www/html
    chdir: /var/www/html
  when: ansible_facts['os_family'] == "Debian"
  ignore_errors: True

# - name: moving files 
#   ansible.builtin.shell: 
#     cmd: cp /var/www/html/wp-config-sample.php /var/www/html/
#     chdir: /var/www/html
#   when: ansible_facts['os_family'] == "Debian"
#   ignore_errors: True

# - name: Change wp-config-sample.php
#   replace:
#     path: /var/www/html/wp-config-sample.php
#     regexp: 'database_name_here'
#     replace: 'wordpress'
#     backup: yes
#   when: ansible_facts['os_family'] == "Debian"

# - name: Change wp-config-sample.php
#   replace:
#     path: /var/www/html/wp-config-sample.php
#     regexp: 'username_here'
  #   replace: 'wpuser'
  #   backup: yes
  # when: ansible_facts['os_family'] == "Debian"

# - name: Change wp-config-sample.php
#   replace:
#     path: /var/www/html/wp-config-sample.php
#     regexp: 'password_here'
#     replace: 'MyP@SS'
#     backup: yes
#   when: ansible_facts['os_family'] == "Debian"

# - name: Change wp-config-sample.php
#   replace:
#     path: /var/www/html/wp-config-sample.php
#     regexp: 'localhost'
#     replace: '134.209.71.38'
#     backup: yes
#   when: ansible_facts['os_family'] == "Debian"

# - name: Copy file with owner and permissions
#   ansible.builtin.copy:
#     src: /var/www/html/wp-config-sample.php
#     dest: /var/www/html/wp-config.php

# - name: moving files and deleting files
#   ansible.builtin.shell: 
#     cmd: touch wp-config.php
#     chdir: /var/www/html
#   when: ansible_facts['os_family'] == "Debian"
#   ignore_errors: True

- name: Fix file ownership
  file:
    path: /var/www/html
    owner: apache
    group: apache
    state: directory
    recurse: yes
  when: ansible_facts['os_family'] == "RedHat"

- name: Fix file ownership
  file:
    path: /var/www/html
    owner: www-data
    group: www-data
    state: directory
    recurse: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Restart httpd
  service:
    name: httpd
    state: restarted
  when: ansible_facts['os_family'] == "RedHat"

- name: Restart apache2
  service:
    name: apache2
    state: restarted
  when: ansible_facts['os_family'] == "Debian"